// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testdraganddrop.proxies;

public class DetailDnD
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject detailDnDMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestDragAndDrop.DetailDnD";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DetailDnD_Detail_DropTarget("TestDragAndDrop.DetailDnD_Detail_DropTarget"),
		DetailDnD_Item_Dragged("TestDragAndDrop.DetailDnD_Item_Dragged"),
		DetailDnD_Detail_Dragged("TestDragAndDrop.DetailDnD_Detail_Dragged"),
		DetailDnD_Header_DropTarget("TestDragAndDrop.DetailDnD_Header_DropTarget");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DetailDnD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestDragAndDrop.DetailDnD"));
	}

	protected DetailDnD(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject detailDnDMendixObject)
	{
		if (detailDnDMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestDragAndDrop.DetailDnD", detailDnDMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestDragAndDrop.DetailDnD");

		this.detailDnDMendixObject = detailDnDMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DetailDnD.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testdraganddrop.proxies.DetailDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testdraganddrop.proxies.DetailDnD.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static testdraganddrop.proxies.DetailDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testdraganddrop.proxies.DetailDnD(context, mendixObject);
	}

	public static testdraganddrop.proxies.DetailDnD load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testdraganddrop.proxies.DetailDnD.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DetailDnD_Detail_DropTarget
	 */
	public final testdraganddrop.proxies.Detail getDetailDnD_Detail_DropTarget() throws com.mendix.core.CoreException
	{
		return getDetailDnD_Detail_DropTarget(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailDnD_Detail_DropTarget
	 */
	public final testdraganddrop.proxies.Detail getDetailDnD_Detail_DropTarget(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testdraganddrop.proxies.Detail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DetailDnD_Detail_DropTarget.toString());
		if (identifier != null)
			result = testdraganddrop.proxies.Detail.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DetailDnD_Detail_DropTarget
	 * @param detaildnd_detail_droptarget
	 */
	public final void setDetailDnD_Detail_DropTarget(testdraganddrop.proxies.Detail detaildnd_detail_droptarget)
	{
		setDetailDnD_Detail_DropTarget(getContext(), detaildnd_detail_droptarget);
	}

	/**
	 * Set value of DetailDnD_Detail_DropTarget
	 * @param context
	 * @param detaildnd_detail_droptarget
	 */
	public final void setDetailDnD_Detail_DropTarget(com.mendix.systemwideinterfaces.core.IContext context, testdraganddrop.proxies.Detail detaildnd_detail_droptarget)
	{
		if (detaildnd_detail_droptarget == null)
			getMendixObject().setValue(context, MemberNames.DetailDnD_Detail_DropTarget.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DetailDnD_Detail_DropTarget.toString(), detaildnd_detail_droptarget.getMendixObject().getId());
	}

	/**
	 * @return value of DetailDnD_Item_Dragged
	 */
	public final testdraganddrop.proxies.Item getDetailDnD_Item_Dragged() throws com.mendix.core.CoreException
	{
		return getDetailDnD_Item_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailDnD_Item_Dragged
	 */
	public final testdraganddrop.proxies.Item getDetailDnD_Item_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testdraganddrop.proxies.Item result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DetailDnD_Item_Dragged.toString());
		if (identifier != null)
			result = testdraganddrop.proxies.Item.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DetailDnD_Item_Dragged
	 * @param detaildnd_item_dragged
	 */
	public final void setDetailDnD_Item_Dragged(testdraganddrop.proxies.Item detaildnd_item_dragged)
	{
		setDetailDnD_Item_Dragged(getContext(), detaildnd_item_dragged);
	}

	/**
	 * Set value of DetailDnD_Item_Dragged
	 * @param context
	 * @param detaildnd_item_dragged
	 */
	public final void setDetailDnD_Item_Dragged(com.mendix.systemwideinterfaces.core.IContext context, testdraganddrop.proxies.Item detaildnd_item_dragged)
	{
		if (detaildnd_item_dragged == null)
			getMendixObject().setValue(context, MemberNames.DetailDnD_Item_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DetailDnD_Item_Dragged.toString(), detaildnd_item_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of DetailDnD_Detail_Dragged
	 */
	public final testdraganddrop.proxies.Detail getDetailDnD_Detail_Dragged() throws com.mendix.core.CoreException
	{
		return getDetailDnD_Detail_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailDnD_Detail_Dragged
	 */
	public final testdraganddrop.proxies.Detail getDetailDnD_Detail_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testdraganddrop.proxies.Detail result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DetailDnD_Detail_Dragged.toString());
		if (identifier != null)
			result = testdraganddrop.proxies.Detail.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DetailDnD_Detail_Dragged
	 * @param detaildnd_detail_dragged
	 */
	public final void setDetailDnD_Detail_Dragged(testdraganddrop.proxies.Detail detaildnd_detail_dragged)
	{
		setDetailDnD_Detail_Dragged(getContext(), detaildnd_detail_dragged);
	}

	/**
	 * Set value of DetailDnD_Detail_Dragged
	 * @param context
	 * @param detaildnd_detail_dragged
	 */
	public final void setDetailDnD_Detail_Dragged(com.mendix.systemwideinterfaces.core.IContext context, testdraganddrop.proxies.Detail detaildnd_detail_dragged)
	{
		if (detaildnd_detail_dragged == null)
			getMendixObject().setValue(context, MemberNames.DetailDnD_Detail_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DetailDnD_Detail_Dragged.toString(), detaildnd_detail_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of DetailDnD_Header_DropTarget
	 */
	public final testdraganddrop.proxies.Header getDetailDnD_Header_DropTarget() throws com.mendix.core.CoreException
	{
		return getDetailDnD_Header_DropTarget(getContext());
	}

	/**
	 * @param context
	 * @return value of DetailDnD_Header_DropTarget
	 */
	public final testdraganddrop.proxies.Header getDetailDnD_Header_DropTarget(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testdraganddrop.proxies.Header result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DetailDnD_Header_DropTarget.toString());
		if (identifier != null)
			result = testdraganddrop.proxies.Header.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DetailDnD_Header_DropTarget
	 * @param detaildnd_header_droptarget
	 */
	public final void setDetailDnD_Header_DropTarget(testdraganddrop.proxies.Header detaildnd_header_droptarget)
	{
		setDetailDnD_Header_DropTarget(getContext(), detaildnd_header_droptarget);
	}

	/**
	 * Set value of DetailDnD_Header_DropTarget
	 * @param context
	 * @param detaildnd_header_droptarget
	 */
	public final void setDetailDnD_Header_DropTarget(com.mendix.systemwideinterfaces.core.IContext context, testdraganddrop.proxies.Header detaildnd_header_droptarget)
	{
		if (detaildnd_header_droptarget == null)
			getMendixObject().setValue(context, MemberNames.DetailDnD_Header_DropTarget.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DetailDnD_Header_DropTarget.toString(), detaildnd_header_droptarget.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return detailDnDMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testdraganddrop.proxies.DetailDnD that = (testdraganddrop.proxies.DetailDnD) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestDragAndDrop.DetailDnD";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
