// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testdraganddrop.proxies;

public class ItemDnD
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject itemDnDMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestDragAndDrop.ItemDnD";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ItemDnD_Item_Dragged("TestDragAndDrop.ItemDnD_Item_Dragged"),
		ItemDnD_Item_DropTarget("TestDragAndDrop.ItemDnD_Item_DropTarget");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ItemDnD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TestDragAndDrop.ItemDnD"));
	}

	protected ItemDnD(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject itemDnDMendixObject)
	{
		if (itemDnDMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TestDragAndDrop.ItemDnD", itemDnDMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TestDragAndDrop.ItemDnD");

		this.itemDnDMendixObject = itemDnDMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ItemDnD.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static testdraganddrop.proxies.ItemDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return testdraganddrop.proxies.ItemDnD.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static testdraganddrop.proxies.ItemDnD initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testdraganddrop.proxies.ItemDnD(context, mendixObject);
	}

	public static testdraganddrop.proxies.ItemDnD load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testdraganddrop.proxies.ItemDnD.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ItemDnD_Item_Dragged
	 */
	public final testdraganddrop.proxies.Item getItemDnD_Item_Dragged() throws com.mendix.core.CoreException
	{
		return getItemDnD_Item_Dragged(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemDnD_Item_Dragged
	 */
	public final testdraganddrop.proxies.Item getItemDnD_Item_Dragged(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testdraganddrop.proxies.Item result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ItemDnD_Item_Dragged.toString());
		if (identifier != null)
			result = testdraganddrop.proxies.Item.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ItemDnD_Item_Dragged
	 * @param itemdnd_item_dragged
	 */
	public final void setItemDnD_Item_Dragged(testdraganddrop.proxies.Item itemdnd_item_dragged)
	{
		setItemDnD_Item_Dragged(getContext(), itemdnd_item_dragged);
	}

	/**
	 * Set value of ItemDnD_Item_Dragged
	 * @param context
	 * @param itemdnd_item_dragged
	 */
	public final void setItemDnD_Item_Dragged(com.mendix.systemwideinterfaces.core.IContext context, testdraganddrop.proxies.Item itemdnd_item_dragged)
	{
		if (itemdnd_item_dragged == null)
			getMendixObject().setValue(context, MemberNames.ItemDnD_Item_Dragged.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ItemDnD_Item_Dragged.toString(), itemdnd_item_dragged.getMendixObject().getId());
	}

	/**
	 * @return value of ItemDnD_Item_DropTarget
	 */
	public final testdraganddrop.proxies.Item getItemDnD_Item_DropTarget() throws com.mendix.core.CoreException
	{
		return getItemDnD_Item_DropTarget(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemDnD_Item_DropTarget
	 */
	public final testdraganddrop.proxies.Item getItemDnD_Item_DropTarget(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		testdraganddrop.proxies.Item result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ItemDnD_Item_DropTarget.toString());
		if (identifier != null)
			result = testdraganddrop.proxies.Item.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ItemDnD_Item_DropTarget
	 * @param itemdnd_item_droptarget
	 */
	public final void setItemDnD_Item_DropTarget(testdraganddrop.proxies.Item itemdnd_item_droptarget)
	{
		setItemDnD_Item_DropTarget(getContext(), itemdnd_item_droptarget);
	}

	/**
	 * Set value of ItemDnD_Item_DropTarget
	 * @param context
	 * @param itemdnd_item_droptarget
	 */
	public final void setItemDnD_Item_DropTarget(com.mendix.systemwideinterfaces.core.IContext context, testdraganddrop.proxies.Item itemdnd_item_droptarget)
	{
		if (itemdnd_item_droptarget == null)
			getMendixObject().setValue(context, MemberNames.ItemDnD_Item_DropTarget.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ItemDnD_Item_DropTarget.toString(), itemdnd_item_droptarget.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return itemDnDMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testdraganddrop.proxies.ItemDnD that = (testdraganddrop.proxies.ItemDnD) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TestDragAndDrop.ItemDnD";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
