// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testdraganddrop.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the TestDragAndDrop module

	public static void iVK_Header_Cancel(IContext context, testdraganddrop.proxies.HeaderDetailDnD _headerDetailDnD)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("headerDetailDnD", _headerDetailDnD == null ? null : _headerDetailDnD.getMendixObject());
			Core.execute(context, "TestDragAndDrop.IVK_Header_Cancel", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_Header_Save(IContext context, testdraganddrop.proxies.HeaderDetailDnD _headerDetailDnD)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("headerDetailDnD", _headerDetailDnD == null ? null : _headerDetailDnD.getMendixObject());
			Core.execute(context, "TestDragAndDrop.IVK_Header_Save", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_Header_StartEdit(IContext context, testdraganddrop.proxies.Header _header)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("header", _header == null ? null : _header.getMendixObject());
			Core.execute(context, "TestDragAndDrop.IVK_Header_StartEdit", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void iVK_Header_StartNew(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "TestDragAndDrop.IVK_Header_StartNew", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void jS_NewItemDropped(IContext context, testdraganddrop.proxies.HeaderDetailDnD _headerDetailDnD)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("HeaderDetailDnD", _headerDetailDnD == null ? null : _headerDetailDnD.getMendixObject());
			Core.execute(context, "TestDragAndDrop.JS_NewItemDropped", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}