// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testdraganddrop.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the TestDragAndDrop module
	public static void iVK_Detail_Reordered(IContext context, testdraganddrop.proxies.DetailDnD _detailDnD)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("detailDnD", _detailDnD == null ? null : _detailDnD.getMendixObject());
			Core.execute(context, "TestDragAndDrop.IVK_Detail_Reordered", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Item_DroppedOnDetail(IContext context, testdraganddrop.proxies.DetailDnD _detailDnD)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("detailDnD", _detailDnD == null ? null : _detailDnD.getMendixObject());
			Core.execute(context, "TestDragAndDrop.IVK_Item_DroppedOnDetail", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Item_DroppedOnHeader(IContext context, testdraganddrop.proxies.DetailDnD _detailDnD)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("detailDnD", _detailDnD == null ? null : _detailDnD.getMendixObject());
			Core.execute(context, "TestDragAndDrop.IVK_Item_DroppedOnHeader", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void iVK_Item_Reordered(IContext context, testdraganddrop.proxies.ItemDnD _itemDnD)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("itemDnD", _itemDnD == null ? null : _itemDnD.getMendixObject());
			Core.execute(context, "TestDragAndDrop.IVK_Item_Reordered", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_Detail_Resequence(IContext context, testdraganddrop.proxies.Header _header)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("header", _header == null ? null : _header.getMendixObject());
			Core.execute(context, "TestDragAndDrop.SUB_Detail_Resequence", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sUB_Item_Resequence(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "TestDragAndDrop.SUB_Item_Resequence", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}